---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test-dockerfile
    image: plugins/docker
    settings:
      repo: nytimes/nginx-vod-module
      dry_run: true
    when:
      event: pull_request

  - name: build-and-push-to-dockerhub
    image: plugins/docker
    settings:
      repo: nytimes/nginx-vod-module
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*
        - refs/heads/master
